onyx_type: config
onyx_id: onyx_config
onyx_data:
  variables_from_env:
    some_great_var: variable_in_environment_name
  variables:
    title: My amazing Onyx Hub
    logo_url: /assets/logo.jpg
    defult_page_template: .
